require "base"
require "vim_opt"

require "lazyInstall"
require "plugs/lazyConfig"
require "plugs/shortScript"
require "plugs/keymapPlugs"
require "plugs/nvim-treesitter"
require "plugs/goLSP"
require "impatient"
